Algoritmo "Veriicador de nota"
// Disciplina   : FPOO
// Professor   : Hebert 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 11/08/2021
Var
// Seção de Declarações das variáveis 
nota: real


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Escreva a nota:")
leia(nota)

se nota > 50 entao
   escreva("aprovado")
fimse
se nota < 50 entao
   escreva("reprovado")
fimse


Fimalgoritmo